# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# VSCode docs https://code.visualstudio.com/api/working-with-extensions/continuous-integration

trigger:
  branches:
    include:
    - master
    - next
    - test
  tags:
    include:
    - v*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> install npm packages"
    npm i && cd tools/js-dos && npm i && cd ../.. 
    echo ">>> installed npm packages"
    echo ">>> Run sample integration test"
    npm run test
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'