allowBuilds:
  '@playwright/browser-chromium': true
  esbuild: true
ignoredBuiltDependencies:
  - '@playwright/browser-chromium'
minimumReleaseAgeExclude:
  - '@xsro/emulators@8.4.0-dosasm0.1 || 8.4.0-dosasm0.2'
