allowBuilds:
  '@playwright/browser-chromium': true
  esbuild: true
ignoredBuiltDependencies:
  - '@playwright/browser-chromium'
minimumReleaseAgeExclude:
  - '@xsro/emulators@8.4.0-dosasm0.1 || 8.4.0-dosasm0.2 || 8.4.0-dosasm0.3 || 8.4.1-dosasm0.1 || 8.4.1-dosasm1.0 || 8.4.1-dosasm1.1'
