
/* eslint-disable */
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.73.7 (0142877a165198f5859777e8460a3249)",
    buildSeed: 1657511324990,
    "wdosbox.shared.wasm": {
        "size": 1477023,
        "gzSize": 506358
    },
    "wdosbox.shared.js": {
        "size": 143644,
        "gzSize": 36441
    },
    "wdosbox.wasm": {
        "size": 1464583,
        "gzSize": 502182
    },
    "wdosbox.js": {
        "size": 124362,
        "gzSize": 32522
    },
    "wlibzip.wasm": {
        "size": 112931,
        "gzSize": 54551
    },
    "wlibzip.js": {
        "size": 76373,
        "gzSize": 19886
    }
,
};
