
/* eslint-disable */
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.73.7 (451fe2e42aca6c1658b2170f3412351b)",
    buildSeed: 1665752077701,
    "wdosbox.wasm": {
        "size": 1955370,
        "gzSize": 556037
    },
    "wdosbox.js": {
        "size": 156829,
        "gzSize": 42848
    },
    "wlibzip.wasm": {
        "size": 117528,
        "gzSize": 54253
    },
    "wlibzip.js": {
        "size": 105835,
        "gzSize": 29285
    }
,
};
