
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.72.0 (48dff6d25baa1a54a3eefb7e18c2afc0)",
    buildSeed: 1631175746472,
    "wdosbox.wasm": {
        "size": 1463621,
        "gzSize": 491837
    },
    "wdosbox.js": {
        "size": 107939,
        "gzSize": 27716
    },
    "wlibzip.wasm": {
        "size": 112343,
        "gzSize": 54127
    },
    "wlibzip.js": {
        "size": 80579,
        "gzSize": 20779
    }
,
};
